### ISSUE TITLE
C# implementation

### ISSUE THREAD

**Issue by tabrath** [libp2p/libp2p#11]
Hi, I've started on a C# implementation of the library. Would you be interested in having it in the organization?

So far I've got a working impl. of the libp2p-crypto module [here](https://github.com/tabrath/cs-libp2p-crypto), but more in the workings. The plan is to implement/port it to modules so it will map to the go impl.

**Comment by daviddias** [comment]
Hi @tabrath! Absolutely, feel free to move it to the org, I'll create  C# team and add you to it :)

Take a look at https://github.com/libp2p/js-libp2p#packages, might help you figure out what are all the pieces too :)

**Comment by tabrath** [comment]
Nice!

**Comment by tabrath** [comment]
Hi, looks like I've got no permission to transfer the repo, or am I doing something wrong?

**Comment by daviddias** [comment]
Even after accepting the invite for https://github.com/orgs/libp2p/teams/c-team ? You can also transfer it to me directly and I transfer it to the org (Github permissions model has these things). You should be able to create repos within libp2p now though

**Comment by tabrath** [comment]
Yes, I accepted the invite, but when I try to transfer the repo to this organization I get "You don’t have the permission to create repositories on libp2p". I did exactly the same thing when I transferred my other repo (cs-multihash) to the multiformats org without any trouble.. Is the team membership causing this, as I'm not part of any team in the multiformats org, but in libp2p?

**Comment by daviddias** [comment]
Figured it out, it was just a missing check box in settings:
![image](https://cloud.githubusercontent.com/assets/1211152/21589768/2a2edf6c-d0ed-11e6-8bc7-c58a8d32354d.png)

**Comment by tabrath** [comment]
Alright, thanks.

**Comment by RichardLitt** [comment]
@tabrath Added you as admin of cs-libp2p-crypto. Any other modules coming, or is that it?

**Comment by tabrath** [comment]
@RichardLitt Yeah, moved over 5 more.

cs-libp2p-peer
cs-libp2p-protocol
cs-libp2p-record
cs-libp2p-io
cs-libp2p-utils

There's a couple more that I haven't moved over yet.. will do soon.

**Comment by daviddias** [comment]
Just changed perms in cs-team to all of the cs repos to be write instead of read -> https://github.com/orgs/libp2p/teams/c-team/repositories

**Comment by daviddias** [comment]
I believe the subject of this issue has been handled, closing :) Reopen if necessary

**Comment by ztl8702** [comment]
Seems like the development of cs-libp2p isn't active for a while. Would like to know how I can contribute.

**Comment by tabrath** [comment]
Hi, it’s just too much for a single person to do, part-time. Could for sure need all help possible as I’d be happy to see this actually running on .net.

I made a little roadmap/status a while ago [here](https://github.com/tabrath/ipfs-roadmap/blob/master/README.md).

Most of the multiformats are working, the simplest libp2p and some ipld modules are just ported from Go, and does not exactly follow .net api-standards.. could need a caring hand 😊

I’d be glad to collaborate with anyone interested, poke me if there’s anything you need help to.
