### ISSUE TITLE
cpp-libp2p build error

### ISSUE THREAD

**Issue by Ben3World** [libp2p/libp2p#112]
when cmake execute here(window 10):
[CMake] -- [hunter] OPENSSL_ROOT: C:/.hunter/_Base/6f54ad8/4800136/7f32a58/Install (ver.: 1.1.1t)
it cann't  continue. who knows what is wrong?

**Comment by dhuseby** [comment]
Hi @Ben3World,

Would you please create an issue in the cpp-libp2p repo here? https://github.com/libp2p/cpp-libp2p/issues

Cheers! 🍻
