### ISSUE TITLE
Decentralized ML framework

### ISSUE THREAD

**Issue by amirjaber** [libp2p/libp2p#116]
**Is your feature request related to a problem? Please describe.**
We are a team of developers building a decentralized blockchain based ML framework. In this work, multiple machines accross internet should connect and send files to each other in each round of training. The head node responsible for aggregating the files that workers has passed to it. Head node should be switched every iteration to make it decentralized. 

**Describe the solution you'd like**
We need a message passing mechanism that provide the IP and status of each node in the network at each iteration. Depending on those information the computers decide which computer to communicate with and send their training files to.

**Describe alternatives you've considered**
We have used http protocol and json files successfully for this communication. 

**Additional context**
We are looking into any message passing library that can work with many computers and has the the feature to update the head node and workers IP to make it decentralized.

**Comment by vletard** [comment]
This is a very interesting project. While I am not anything close to specialist on libp2p, I am working on a somewhat similarly structured project (supporting decentralized backup instead of ML in my case).

For what it's worth :
I use the Libp2pStreamMounting feature from the kubo system that permits direct connection to any known node. The same thing is certainly possible using an implementation of libp2p directly, but I am using Python and py-lip2p does not offer that feature yet.

**Comment by amirjaber** [comment]
Thanks, we are also using Pyhon and would like to find a solution in Python. I appreciate if you can explain your Libp2pStreadMounting solution and also if someone else from Libp2p can clarify if there is a native solution for python in their package.

**Comment by vletard** [comment]
Kubo's [Libp2pStreamMounting](https://github.com/ipfs/kubo/blob/master/docs/experimental-features.md#ipfs-p2p) tunnels p2p connections and interfaces with local TCP by opening local ports.
Most of the work here is setting up the redirections between local and p2p connections (and communicating/keeping track of peer IDs). Once this is done, the whole project can communicate using the redirected endpoints just like there was no p2p. Check the above link for the CLI usage, you can also use kubo's API instead I believe.

And I would also be very interested if anyone can point to a Python-native solution.

**Comment by mxinden** [comment]
> Thanks, we are also using Pyhon and would like to find a solution in Python.

py-libp2p is not maintained. Your best bet is to bind to one of the other implementations. I would expect this to be reasonably easy with rust-libp2p and go-libp2p.

**Comment by dhuseby** [comment]
> py-libp2p is not maintained.

Yes it is. @pacrob and myself are maintaining [py-libp2p](https://github.com/libp2p/py-libp2p/). It is behind on a lot of features but we could use the help getting it caught up.

**Comment by dhuseby** [comment]
The best place for this discussion is to post it into Ideas in the [py-libp2p discussion forum](https://github.com/libp2p/py-libp2p/discussions/categories/ideas)
