### ISSUE TITLE
Make an implementation of libp2p

### ISSUE THREAD

**Issue by David00154** [libp2p/libp2p#119]
Are there any guidelines or tutorials for implementing libp2p in another programming language, e.g rugby or crystal?

**Comment by Stebalien** [comment]
No, implementing libp2p is generally a pretty large undertaking. I'd recommend:

1. Read an implementation in a language you're comfortable with (and read the specs at the same time).
2. Implement enough to get it functional (focus on one transport stack).
3. Read the go implementation as it tends to be the most feature complete.
4. Continue to strive for feature parity.

If you want to discuss this more, I recommend you head over to https://discuss.libp2p.io/. You're not going to get much engagement here.
