### ISSUE TITLE
Level both implementations

### ISSUE THREAD

**Issue by daviddias** [libp2p/libp2p#16]
With the increasing interest in libp2p, with the website coming up and with other implementations and uses popping, we need more than ever to start nailing down and matching our building blocks, by this I mean: names, modules scope, behavior, etc.

@whyrusleeping I feel me and you can tag along for a week and get a lot of this done, how do you feel about last week of March?

We would:

- Create a diagram of all the pieces tied together
- Create interface definitions for Go
- Build the DHT in JS
- Create examples with a language that applies to both programming languages

**Comment by dignifiedquire** [comment]
There is also this proposal for the docs sprint: https://github.com/ipfs/docs/issues/15 which I intended to cover things like naming conventions, module scopes and readmes.

**Comment by daviddias** [comment]
From https://github.com/ipfs/docs/issues/15, we also need:

- README unification
- Naming convention
