### ISSUE TITLE
Amazing lists of P2P Knowledge, tools and more

### ISSUE THREAD

**Issue by daviddias** [libp2p/libp2p#20]
A good way to get a broad view of what is out there in the P2P space is by checking the [awesome lists](https://github.com/sindresorhus/awesome) about P2P. The ones I found so far are:

- https://github.com/kgryte/awesome-peer-to-peer
- https://github.com/mafintosh/awesome-p2p
- https://github.com/retrohacker/awesome-p2p
- https://github.com/steve-vincent/awesome-decentralized
- https://github.com/hackerkid/Awesome-P2P

**Comment by raulk** [comment]
This is awesome. I referenced it from #56, so I'll close this issue down since there's more activity in the other one.
