### ISSUE TITLE
Where is the repo for the Java implementation?

### ISSUE THREAD

**Issue by kg6zvp** [libp2p/libp2p#21]
Your website lists a Java implementation as "in progress." Is the repo on a different site? Do you need any help with it?

**Comment by ghost** [comment]
Sorry, that language matrix is outdated in all kinds of ways. To my knowledge there's no java-libp2p being worked on.

**Comment by dashm8** [comment]
and what about a python implementation?

**Comment by raulk** [comment]
@dashm8 for a Python implementation, you can check out [py-libp2p](https://github.com/zixuanzh/py-libp2p/) (in incubation). It'll likely be transferred to the libp2p organisation soon as our Python native implementation.

**Comment by zhfnjust** [comment]
i think android need a libp2p

**Comment by keepsimple1** [comment]
Looks like this topic was last updated more than one year ago, is there any new update regarding Java implementation?

**Comment by raulk** [comment]
jvm-libp2p (written in Kotlin) in the works here: https://github.com/web3j/libp2p

Still in early stages. Open an issue in that repo if you’d like to get involved! 🙌

**Comment by keepsimple1** [comment]
Thanks! That's awesome! 👍

**Comment by keepsimple1** [comment]
Kotlin seems to be pretty popular with Android development. I poked around a bit with Kotlin and it seems to me it's actually quite different from Java (I'm totally new to Kotlin). Just curious, anyone is doing Java implementation? (it will be easier for me to contribute :) )

**Comment by raulk** [comment]
It’s worth to invest in learning Kotlin. Much nicer than pure Java; far superior on all accounts. It compiles down to JVM bytecode and interoperates seamlessly with Java code. With this implementation in existence, I doubt there will be a pure Java one. Kotlin is not just used in Android.
