### ISSUE TITLE
libp2p service (aka Daemon)

### ISSUE THREAD

**Issue by daviddias** [libp2p/libp2p#22]
> Some context on https://github.com/libp2p/interop/issues/1

This issue is here as placeholder for discussion around the libp2p service

**Comment by ghost** [comment]
I'm just gonna throw some brief notes here:

- Environments
  - web browsers
  - daemons
  - desktop tools (e.g. network manager)
  - any program communicating over libp2p
  - linux kernel
  - core internet routers/switches (e.g. openflow)
  - mobile devices
  - embedded devices (home routers, raspberries, printers, toasters, etc.)
- Daemon
  - Instead of IPFS's current daemon model, where you can mostly provide configuration only at startup, I'd like to do something closer to cjdns's daemon model. The daemon always starts with a bare-minimum configuration (key material, and the API address to bind to), and a user space tool is used to configure the daemon through the API.
  - This would give us hot config reloads, which are very important to have in networking software.
- CLI examples
  - ```sh
    > libp2pctl node add foo
    Created node
      /p2p/QmFoosPeerID

    > libp2pctl start foo
    Starting node
      /p2p/QmFoosPeerID
    API listening on
      /unix/var/run/libp2p/foo/api.sock

    > libp2pctl listen foo /ip4/0.0.0.0/tcp/4001
    Loading transports
      /ip4
      /tcp
    Swarm listening on
      /ip4/0.0.0.0/tcp/4001/p2p/QmFoosPeerID
    Saving configuration changes
      ok.

    # then the ipfs daemon uses the libp2p node api to bind its bitswap handler (unix socket or whatever) to the node 
    > libp2pctl bind foo /ipfs/bitswap/1.0.0 /unix/var/run/ipfs/bitswap.sock

    > libp2pctl status foo
    Node healthy
      /p2p/QmFoosPeerID
    API listening on
      /var/run/libp2p/foo/api.sock
    Swarm listening on
      /ip4/0.0.0.0/tcp/4001
    Have 3 active protocols
      /libp2p/id/1.0.0 as internal
      /libp2p/kad-dht/1.0.0 as /var/run/ipfs/dht.sock
      /ipfs/bitswap/1.0.0 as /var/run/ipfs/bitswap.sock
    Have 46 connections
      12 /ip4/tcp
      34 /ip6/udp
    Have 67 open streams
      46 /libp2p/id/1.0.0
      21 /libp2p/kad-dht/1.0.0
    ```

**Comment by paralin** [comment]
@lgierth I'm working on a prototype of what you describe here now and should have something thrown together by tonight.

**Comment by paralin** [comment]
@lgierth I don't have as much done as I'd like due to some other projects taking too much time (grr), but here's my initial work: https://github.com/paralin/go-p2pd

A little demo of node creation: https://asciinema.org/a/zSIXd5at5WqPMKPN86i6sEucy

**Comment by daviddias** [comment]
Nice going @paralin 👏🏽

**Comment by paralin** [comment]
@lgierth OK, small update: https://asciinema.org/a/3HEUSN35CXQWVtD4RmsISNUBX

Implemented:

 - node add
 - node start
 - node status
 - node list
 - node listen

**Comment by ghost** [comment]
@paralin that looks pretty sweet.

I have a slightly different approach in mind, that can accelerate the daemon work greatly. We could reuse the commands lib used in go-ipfs, and thus save the daemon from getting blocked by extensive API design. We know it works reasonably okay-ishly and we know its issues. It won't be a high-performance API as it should eventually be, but it'd be more than fine for a first HTTP-based iteration.

**Comment by Stebalien** [comment]
> I have a slightly different approach in mind, that can accelerate the daemon work greatly. We could reuse the commands lib used in go-ipfs

So, yes, this will allow us to reuse a bunch of code. And yes, unifying an API and a CLI is an interesting and cool idea. However, evolving an API is tricky so I'd like to take some time to think through this. The commands library in go-ipfs has some significant drawbacks. Many of these can probably be avoided but we'll have to be careful.

* It has poor error handling. We have *two* error paths, commands can theoretically return multiple errors, and we use duck typing to determine if something is an error or a result. However, the next release should improve this a bit. I'd like to remove the duck typing *entirely* before we start using it in a libp2p daemon.
* It still has race conditions. It's getting better but many of the code paths in the commands library are convoluted and hard to reason about.
* Poor performance. There are places where we end up parsing things twice for various reasons. These can be improved, it's just time consuming and hard to do without breaking other things (again, convoluted code paths).
* It mixes a user interface with an API. This was kind of the point of the library but command-line argument parsing should be done by a client, not a server. This makes the API significantly less nice to use from another program (the *primary* usecase for the libp2p daemon). It also means that passing non-file binary objects is pretty damn difficult to impossible (without additional manual encoding).
* It uses mime multipart encoding for directory uploads (makes it hard to program/script against if you want to upload multiple files). May not be an issue for libp2p but still baggage we need to carry.
* It puts some of the arguments in the URL but allows others to be streamed in the body (newline separated).

Having implemented this in JS, I'm sure @diasdavid would like to chime in.

**Comment by kevleyski** [comment]
I was reading there was an intention this becomes part of the Linux Kernel - just wondering if that happened, or if happening maybe I might be able to help
(I'm looking at this in the context of optimization of both IPFS and Etherium2)

**Comment by Stebalien** [comment]
There is now a daemon implementation (go-libp2p-daemon). There is no in-kernel implementation and it's not planned in the near future (but might be nice eventually).

**Comment by achingbrain** [comment]
There is a js equivalent [here](https://github.com/libp2p/js-libp2p-daemon) - it's largely used for interop testing.  Further discussion (if required) should happen there.

**Comment by paralin** [comment]
I'm still working on a libp2p daemon - dynamically configurable, supporting flexible yaml files to configure the controllers - see [Bifrost](https://github.com/aperturerobotics/bifrost). 

This is the continuation of the work I posted about in here in 2017 towards a libp2p "daemon" to share resources between other processes.

I see that go-libp2p-daemon is not actively being developed
