### ISSUE TITLE
GRPC over libp2p

### ISSUE THREAD

**Issue by paralin** [libp2p/libp2p#26]
I have successfully routed GRPC over a libp2p stream in Go, and it was actually pretty trivial. I'm working on bundling together a go-libp2p-grpc package at the moment, although that shouldn't take more than 10 minutes.

I'm thinking more now on the browser side. There is a project called grpc-web, that is probably still private, that Google invites contributors to.  https://github.com/grpc/grpc-web

It is designed to allow the browser to directly connect to a GRPC server, which makes sense. What if we re-purposed the GRPC node code to run in the browser with GRPC-over-libp2p? This should be pretty trivial - just replace the Buffer implementation with ByteBuffer.js or so, and tweak a few things.

**Comment by paralin** [comment]
I released the initial version of the package here:

 - https://github.com/paralin/go-libp2p-grpc

Could use some help with GX but that's beside the point

**Comment by james-lawrence** [comment]
related and likely a better solution in case anyone else runs into this issue like i did: https://github.com/libp2p/go-libp2p-gostream
```golang
import (
	"github.com/libp2p/go-libp2p-core/host"
	gostream "github.com/libp2p/go-libp2p-gostream"
)
func bind(h host.Host) error {
	if bind, err = gostream.Listen(h, "myprotocol"); err != nil {
		return errr
	}
        srv := grpc.NewServer()
        return server.Serve(bind)
}
```

**Comment by Stebalien** [comment]
(closing as stale)

It would be nice to get a nexample in go-libp2p-examples some time.
