### ISSUE TITLE
Wrong go-lang implementation link

### ISSUE THREAD

**Issue by resilva87** [libp2p/libp2p#3]
Hi!

Just to notify you, the link pointing to golang implementation in README is wrong. It points to https://github.com/libp2p/go-libp2p where I think the correct is https://github.com/ipfs/go-libp2p

**Comment by jbenet** [comment]
It needs to be moved. 
- [x] transfer ipfs/go-libp2p to libp2p/go-libp2p  

@whyrusleeping leaving for you as am not sure if it will break anything (gx, etc)

**Comment by whyrusleeping** [comment]
Nah, moving that won't break anything (gx keeps things rather solid). I'll go ahead and do it now.

**Comment by daviddias** [comment]
This is done now :)
