### ISSUE TITLE
How to get the libp2p source code?

### ISSUE THREAD

**Issue by ansili** [libp2p/libp2p#42]
How to get the libp2p source code?
How to compile C++version？

**Comment by Stebalien** [comment]
I'm not aware of any C++ implementations of libp2p. However, there's a [go version](https://github.com/libp2p/go-libp2p) and an experimental [rust version](https://github.com/libp2p/rust-libp2p) that may suit your needs.

---

Closing for tracking purposes. Fell free to ask followup questions.

**Comment by ansili** [comment]
Thanks, I need C++version.
@Stebalien
