### ISSUE TITLE
Mid-Quarter OKR Scoring

### ISSUE THREAD

**Issue by ghost** [libp2p/libp2p#43]
Hello friends,

It's that time of the quarter... the middle!  And that means big fun:  mid-point scoring of OKRs.

Background on what we do at mid-quarter:  https://github.com/ipfs/pm/issues/668

For libp2p, I want to follow the same process as David's issue above.  I'd like each KR owner to assign a mid-quarter score to your KRs this week.  On next week's call, we'll do a check-in as @diasdavid describes in https://github.com/ipfs/pm/issues/668.  

Updating the OKR sheet is a great opportunity to communicate how things are going, where you might need help, thoughts on whether we should change plans, concerns or frustrations, etc.

Remember that we're mostly focused on the P0s for this quarter.  But let's score everything.

@bigs:  You have P0 OKRs on the [Rust tab](https://docs.google.com/spreadsheets/d/1HTXfgR5FyPTFhsTkFPRThkeMvHvCgJOaAs7BSl_vQ_0/edit#gid=62056007), [Go tab](https://docs.google.com/spreadsheets/d/1HTXfgR5FyPTFhsTkFPRThkeMvHvCgJOaAs7BSl_vQ_0/edit#gid=1240336497) and [PL tab](https://docs.google.com/spreadsheets/d/1HTXfgR5FyPTFhsTkFPRThkeMvHvCgJOaAs7BSl_vQ_0/edit#gid=2004927323).

@diasdavid:  You have P0s on the [JS tab](https://docs.google.com/spreadsheets/d/1HTXfgR5FyPTFhsTkFPRThkeMvHvCgJOaAs7BSl_vQ_0/edit#gid=1241853194), [overall project tab](https://docs.google.com/spreadsheets/d/1HTXfgR5FyPTFhsTkFPRThkeMvHvCgJOaAs7BSl_vQ_0/edit#gid=0).

@marten-seemann:  You have P0's on [Go tab](https://docs.google.com/spreadsheets/d/1HTXfgR5FyPTFhsTkFPRThkeMvHvCgJOaAs7BSl_vQ_0/edit#gid=1240336497), [overall project tab](https://docs.google.com/spreadsheets/d/1HTXfgR5FyPTFhsTkFPRThkeMvHvCgJOaAs7BSl_vQ_0/edit#gid=0)

@Stebalien:  You have P0s on [Go tab](https://docs.google.com/spreadsheets/d/1HTXfgR5FyPTFhsTkFPRThkeMvHvCgJOaAs7BSl_vQ_0/edit#gid=1240336497), [PL tab](https://docs.google.com/spreadsheets/d/1HTXfgR5FyPTFhsTkFPRThkeMvHvCgJOaAs7BSl_vQ_0/edit#gid=2004927323)

@jacobheun & @vasco-santos:  You both have P0's on the [JS tab](https://docs.google.com/spreadsheets/d/1HTXfgR5FyPTFhsTkFPRThkeMvHvCgJOaAs7BSl_vQ_0/edit#gid=1241853194)

@whyrusleeping:  You have P0s on the [Go tab](https://docs.google.com/spreadsheets/d/1HTXfgR5FyPTFhsTkFPRThkeMvHvCgJOaAs7BSl_vQ_0/edit#gid=1240336497), [PL tab](https://docs.google.com/spreadsheets/d/1HTXfgR5FyPTFhsTkFPRThkeMvHvCgJOaAs7BSl_vQ_0/edit#gid=2004927323)

@mgoelzer:  I've scored all my P0's.  I'll make another pass to get the others scored.  Oh, and I'll fix those broken formulae at the top. 

/ cc @lgierth (you have some P1 KRs)

/ cc @raulk (for general interest)

**Comment by daviddias** [comment]
✅ `@diasdavid: You have P0s on the JS tab, overall project tab.` Note that the Overall Project Tab ones are just the reflection of OKRs on the JS tab

**Comment by ghost** [comment]
Closing - thanks everyone.
