### ISSUE TITLE
libp2p daemon to test basic DHT operations

### ISSUE THREAD

**Issue by ghost** [libp2p/libp2p#45]
@bigs DHT goal for September

- libp2p daemon with the bare functionality required to do basic DHT ops (like put and read back keys)
- Just running on one machine
- Leave out IPTB for now

Ref: https://docs.google.com/document/d/1XOmU-9V6yx0tMcW9iVeL9nNSgrPDt5X7aBmRzD2ZO34/edit

**Comment by raulk** [comment]
@mgoelzer I'm closing this issue since the wish has been addressed in [go-libp2p-daemon](https://github.com/libp2p/go-libp2p-daemon/) with both daemon API and client bindings operational.
