### ISSUE TITLE
Q4 OKR Planning

### ISSUE THREAD

**Issue by ghost** [libp2p/libp2p#50]
This issue is to track Q4 libp2p OKR planning.  [Please see the current work-in-progress sheet.](https://docs.google.com/spreadsheets/d/1BYwmbVicgo6_tOHAbgiUXWge8Ej0qR1M_gAUulazmrg/edit#gid=0)

Here's the status:
- I have simplified the structure based team feedback:  4 tabs (Project, JS, Go, Rust), fewer cross-sheet dependencies and roll up cells
- I have defined and filled in a high level Project goals tab
- Following discussions with many of you yesterday, I have added some opportunistic new O's around things like Ethereum community adoption, etc.
- I removed all the Q3 KRs.  If there were important and left unfinished, the language teams should resurrect them.

Here is what I'm asking:
- I would appreciate everyone's feedback on the Project goals tab.  I don't seek to be dictator for this tab; just putting forward a first draft.
- JS team + David - can you define your specific technical OKRs such as features and fixes for js-libp2p on the JS tab?
- Go team + David - ditto for Go tab
- Rust team + Pierre - ditto for Rust tab

Ideally, these should align with the overall project goals we agree to in the Project tab.  My hope is that we'll converge through a bottom-up and top-down combination, like last quarter.

Comments welcome in the doc or this issue.

**Comment by jacobheun** [comment]
For reference the JS working OKR discussion is here, https://github.com/libp2p/js-libp2p/pull/247, and I have added a comment on my thoughts for Q4 objectives. Some of them are currently high level, but we can make them more measurable as we confirm them.

**Comment by ghost** [comment]
@jacobheun Thanks, it's a great discussion.  I'll take my comments over there.

**Comment by ghost** [comment]
Let's use this issue to discuss overall project goals ([this tab](https://docs.google.com/spreadsheets/d/1BYwmbVicgo6_tOHAbgiUXWge8Ej0qR1M_gAUulazmrg/edit#gid=0)) and/or cross language issues.
