### ISSUE TITLE
Partial (or selective) Uploading of Video or Photo Files

### ISSUE THREAD

**Issue by doctorrobinson** [libp2p/libp2p#52]
If i've uploaded a version of a video, is it possible to submit a revision in which only the pieces that are changed need to be uploaded? 

For example, I have a 10 minute video that encodes to 10GB in size. I upload it. A client wants me to replace their logo at the start of the video with a different one. I've made one small change to the first 10seconds, but it's still a 10 minute, 10 GB video. Can it only upload the changed sections, saving me large amounts of data transfer?

The same would apply to a large .tiff file. If I only change a few pixels, is there a way to only upload the change?

@jacobheun

**Comment by Stebalien** [comment]
So, I'm going to be a stickler (sorry) and say, ask at: https://discuss.ipfs.io/ (this is an IPFS issue, not a libp2p issue).
