### ISSUE TITLE
libp2p Multi-Year Roadmap

### ISSUE THREAD

**Issue by ghost** [libp2p/libp2p#60]
@raulk and I, along with the help of many others, are beginning the process of devising a multi-year roadmap for libp2p.  The ongoing working document is here:  [libp2p Roadmap Document](https://docs.google.com/document/d/1Rd4yNw1TNQBvfRrKeEMSTseb6fvPzS-C--obOn0nul8/edit).

As a first iteration, this document is a long enumeration of all the possible goals for the project.  We aren't necessarily going to pursue all of these goals, but having them all in one place is a useful starting point.

We're now entering a phase where we will define a set of high level objectives for the project, unpack them into specific goals, and decide what is in/out of scope, what is urgent vs. back-burner, etc.  That process will also happen in the same working document.

Anyone with an interest in the project is welcome to participate in this discussion.  Right now, the best way is to make suggestions in the document or in this issue.  As we get closer to something final, we'll convert it to markdown, open a PR here, and maintain the document in this repo.  In the meantime, come join us in the document and help shape the future of the libp2p project.

**Comment by raulk** [comment]
Closing as this already served its purpose: to notify the community that the roadmap exists.
