### ISSUE TITLE
Add ROADMAP.md

### ISSUE THREAD

**Issue by ghost** [libp2p/libp2p#68]
We should add a ROADMAP.md that reflects the latest quarter by quarter roadmap we have discussed in the project.  

While I also want to highlight the information in #60, what I think most people expect from a roadmap is what's coming this quarter, next quarter, next year, etc.  Self-assigning this.

**Comment by mxinden** [comment]
Assigning this to me. I hope you don't mind @mgoelzer.

I will write a basic high-level roadmap. Concrete timelines could be added in a follow-up pull request if need be.

//CC @marten-seemann
