### ISSUE TITLE
slack is better than irc

### ISSUE THREAD

**Issue by jinleileiking** [libp2p/libp2p#75]

**Comment by tesla809** [comment]
I would agree with this. Why not support both chat rooms?

**Comment by Stebalien** [comment]
We now tend to use matrix (bridged to IRC and discord). While I believe it's possible to bridge slack and matrix, it's a non-trivial amount of work. We could have two separate rooms but then devs would have to pay attention to and participate in both.

So the answer is: we may set it up eventually, but it's a non-trivial amount of work and not a high priority. For now, please use either Matrix (Riot), Discord, or IRC (freenode).

**Comment by jinleileiking** [comment]
@Stebalien Thanks。 What is the Matrix link? thanks.

**Comment by Stebalien** [comment]
[#libp2p:matrix.org](https://matrix.to/#/#libp2p:matrix.org)
