### ISSUE TITLE
OUTDATED: waffle badge on README

### ISSUE THREAD

**Issue by 0zAND1z** [libp2p/libp2p#80]
Now that waffle.io is long gone, we must update the badge and keep it relvant to the current efforts.

May I propose to manage all libp2p work items under [ZenHub](https://www.zenhub.com/)?

This thread might be helpful : https://github.com/ipfs/team-mgmt/issues/930

**Comment by raulk** [comment]
@0zAND1z thanks for catching this. We will be running an ZenHub experiment on go-libp2p shortly: https://github.com/libp2p/go-libp2p/issues/676. Based on the results, we will evaluate getting all libp2p implementations on ZenHub, which will simplify tracking cross-implementation epics.
