### ISSUE TITLE
Transport-level compression support

### ISSUE THREAD

**Issue by raulk** [libp2p/libp2p#81]
This issue is a placeholder; I'll expand on it later.

Ethereum 2.0 might be interested in transparently compressing streams payloads. We need to research how this would be feasible without participation from the application layer. Many protocols length-prefix messages. How would boundaries be identified if all data is compressed? Can we do this without buffering?

The LZ4 algo supports streams: https://lz4.github.io/lz4/

CC @agemanning @arnetheduck

**Comment by Stebalien** [comment]
Ideally, we'd just use multistream to negotiate compression. For example, when connecting to a service, one would first negotiate `/compression/lz4`, then the actual protocol.

**Comment by mxinden** [comment]
Closing here in favor of https://github.com/libp2p/specs/issues/485.
