### ISSUE TITLE
Slack or Discord Channel is needed for developers to chat

### ISSUE THREAD

**Issue by tesla809** [libp2p/libp2p#83]
Libp2p is the perfect for people interested in learning more about:
A) Rust via contributing to a real project
B) Distributed systems

But on-boarding devs is not straight forward.

A Slack (preferable), discord or mastodon node is needed where developers can chat in real time. Slack is easier because people already have it. It may be less cool, but there is less friction with getting people to use it. I have a couple of developer friends who are interested in contributing to Rust Implementation of Libp2p, but on-boarding is not straight forward. 

The community can be leveraged to create "stickiness" via social interactions and push people down the marketing and contribution funnel. A lot of information that is given over the chat can then be codified into Docs.

This strategy is starting to work for NYC Blockchain Devs Meetup and is starting to yield results in finding talented devs looking for projects to contribute to.

**Comment by mkg20001** [comment]
There's an IRC channel #libp2p on freenode.net

**Comment by Stebalien** [comment]
You can also join #libp2p:matrix.org (matrix) or via discord (http://permaweb.io/discord). All are bridged into the same room.

**Comment by tesla809** [comment]
Sure, but that doesn't address the question. If you want more developers to join, you have to lower the friction on the user on-boarding on all aspects of the product. Chat is one of those areas. 

One of the ideas in marketing is to go where the users are, not where you want to be, lol.

**Comment by tesla809** [comment]
Looks better. I was not aware that there was a discord channel. Perhaps this information should be clearly mentioned on the main website and repos.

**Comment by mirogta** [comment]
Slack channel would be great… permaweb.io domain has expired

**Comment by kanishkatn** [comment]
Please update the Discord link

**Comment by mxinden** [comment]
Closing here with https://github.com/libp2p/libp2p/pull/98 pointing to the Matrix channel.

Feel free to comment in case you have additional suggestions.

In general, please use discuss.libp2p.io/ instead of _ephemeral_ chat conversations for questions / discussions / suggestions, given that answers are persisted and thus discoverable for future users.
