### ISSUE TITLE
Write down @lgierth Milestones

### ISSUE THREAD

**Issue by daviddias** [libp2p/libp2p#9]
https://github.com/libp2p/libp2p/blob/master/ROADMAP.md#milestones-to-be-added

**Comment by ghost** [comment]
Yep getting to it now. Last week was terribly slow for me.

On an unrelated note @diasdavid, do you mind if I apply the same style changes to the roadmap document as I did for Q3? I find it very very hard to read at the moment, there are just so many headings.

**Comment by daviddias** [comment]
@lgierth sounds good to me :)

**Comment by ghost** [comment]
here #10
