### ISSUE TITLE
proxy

### ISSUE THREAD

**Issue by ojej** [libp2p/libp2p#94]
Chinese user dont have ifps
is possible add protocol tox ? similar https://github.com/gjedeer/tuntox to use tox or matrix as communication for libp2p.

**Comment by Stebalien** [comment]
It's possible to tunnel libp2p traffic over any protocol, really. The websocket transport already uses the system's http proxy for outbound connections.

**Comment by ojej** [comment]
please one ;-)

**Comment by mxinden** [comment]
Closing here due to missing details and stalled conversation. @ojej feel free to comment to continue the conversation.
