### ISSUE TITLE
PJON transport

### ISSUE THREAD

**Issue by gioblu** [libp2p/libp2p#95]
Ciao, compliments and thank you for the amazing work done on this project. 
One question, have you ever seen PJON: https://github.com/gioblu/PJON
Is there a chance it could become one of the supported transports?

**Comment by Stebalien** [comment]
There's no reason it can't be. You'd need to:

1. Implement a transport like https://github.com/libp2p/go-tcp-transport.
2. Register a codec for the protocol: https://github.com/multiformats/multiaddr/.

**Comment by mxinden** [comment]
I am closing here. In case you would like to continue this effort @gioblu, please open up a pull request with a minimal specification on https://github.com/libp2p/specs/ so we can coordinate all upcoming efforts.
